language: node_js
node_js:
  - '10'
  - '8'
branches:
  only:
    - master
    - /^greenkeeper/.*$/
script:
  - npm run build
  - npm run test-cov
after_script: "npm i coveralls && cat ./coverage/lcov.info | coveralls"
